Repository Eclalang/Ecla, pull requests merged in 2024-02, with the labels that each got.

#225 readded the struct parsing condition
  parser/Parser.go
Labels: fixed

#227 Issue #203 adding compatible lists
  interpreter/eclaType/char.go
  interpreter/eclaType/list.go
Labels: fixed

#240 fixed errors in various release demo files
  DEMO/Release/brainfuck.ecla
  DEMO/Release/fibonacci.ecla
  DEMO/Release/hangman.ecla
Labels: fixed

#274 added unit testing for metrics tools
  metrics/metrics.go
  metrics/metrics_test.go
Labels: test

#281 removed redundant checks
  interpreter/eclaType/int.go
Labels: fixed

#288 implemented int xor float and char xor float
  interpreter/eclaType/char.go
  interpreter/eclaType/int.go
Labels: implemented
